### ISSUE TITLE
Provide pre-compiled application packaged with trace server

### ISSUE THREAD

**Issue by ebugden** [theia-ide/theia-trace-extension#352]
In some cases, if users want to visualize their own traces, they still need to do the full complicated dev setup. The live demo allows users to upload traces, but this is not safe for private traces and not possible for very large traces. Providing a downloadable binary is a nice midway point between the live demo and the full dev setup.

- [x] **Build electron app packaged with server for Linux**
- [x] **Shrink packaged application to reasonable size range** - @arfio completed a quick package (it is 600 MB which is a large for a typical electron app #378) 
- [x] **Test app works without requiring external dependencies** - @arfio and @thefinaljob successfully tested the app on a clean install of Ubuntu. 
   - The only missing dependency is Java which needs to be installed manually before using the app #377. 
   - Packaged app only works on a full Linux VM or native Linux (does not work using the Windows subsystem for Linux (wsl) command)
- [x] **Host app permanently on publicly available server** (Github has a file size limit of 100 MB) - The app package is hosted [here](https://www.dorsal.polymtl.ca/files/other/electron-theia-trace-example-app-0.0.1.AppImage) on a DORSAL lab server (a main project contributor). @thefinaljob says it takes a few minutes to download (~5 on slower wifi).
- [x] **Upstream changes required to package application** with the server (PR #594) - This makes it easy to periodically generate an updated version of the package that can then be made publicly available
- [x] **Update Github readme** with: (PR #392)
   * **Link to application**, **build date** (so users know how old the build is), specify that installing **Java is required**
   * Specify that currently it's not possible to view your own traces with the live demo, and that to view your own traces you need to install the tool.
- [ ] **Automate?** building, packaging and updating the app (update twice a month?)

* ~~**Put everything in a Docker container?** So that users don't have to install Java (would have to install Docker instead)~~ Java is easier to install than Docker for Linux users so that will be the dependency (arfio [comment](https://github.com/theia-ide/theia-trace-extension/pull/392#discussion_r669860963))
   * ~~This will be more of an issue once we can build packages for Windows (because Java is awkward to install on Windows)~~
   * ~~On Linux Java is not difficult to install, but people have an aversion to it~~

----

Related: #59

**Comment by ebugden** [comment]
- [x] **Build electron app packaged with server for Linux** - @arfio completed a quick package (it is 600 MB which is a large for a typical electron app) 
- [x] **Test app works without requiring external dependencies** - @arfio and @thefinaljob successfully tested the app on a clean install of Ubuntu. The only missing dependency is Java which needs to be installed manually before using the app #377. 
- [ ] **Host app permanently on publicly available server** (Github has a file size limit of 100 MB)
- [ ] **Update Github readme** with link to application, build date (so users know how old the build is), and specify that installing Java is required
- [ ] **Automate** building, packaging and updating the app (update twice a month?)

**Comment by ebugden** [comment]
Updates (that could make the current approach proposed in #387 less relevant?): 
* The trace viewer was recently published to NPM:
   * Extension: [theia-traceviewer](https://www.npmjs.com/package/theia-traceviewer)
   * Packages: [traceviewer-base](https://www.npmjs.com/package/traceviewer-base), [traceviewer-react-component](https://www.npmjs.com/package/traceviewer-react-components)
* It's possible to upload files to the Gitpod demo. Whether it takes a reasonable amount of time to upload a 1 GB trace has not been tested yet. If it doesn't take years to upload this PR is less relevant.

**Comment by ebugden** [comment]
* @arfio Recently updated the application package [available in the readme](https://github.com/theia-ide/theia-trace-extension#download-an-external-build-of-the-application).
* #594 Adjusted how the electron app is bundled to make the app package easy to generate
